Tailormap/tailormap-api

.github/dependabot.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release-drafter.yml, build/qa/pmd-junit-ruleset.xml, build/qa/pmd-ruleset.xml, pom.xml
and fix dependabot config, replce deprecated PMD rules
=> Dependency updates

.github/workflows/ubuntu-maven.yml, .reuse/dep5, pom.xml, src/main/java/nl/b3p/tailormap/api/controller/VersionController.java, src/main/resources/application.properties, src/site/site.xml, src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
And publish the Maven site at https://b3partners.github.io/tailormap-api after succesful build of main branch
=> read version from properties and add integration test

src/main/resources/model.yaml, src/main/resources/statusresponses.yaml, src/main/resources/tailormap-api.yaml
This API will be augmented with component specific API calls that can retrieve and or manipulate data.
close TM-289 / HTM-25
=> [HTM-25] initial OpenAPI contract for tailormap-api

.github/maven-settings.xml, .github/workflows/ubuntu-maven.yml, README.md, pom.xml
=> [HTM-35] Verplaats docker image hosting naar github packages

.github/workflows/ubuntu-maven.yml, Dockerfile
the timeout is needed for `2021-12-14 12:50:24.677  WARN 1 --- [           main] o.s.boot.StartupInfoLogger               : InetAddress.getLocalHost().getHostName() took 5016 milliseconds to respond. Please verify your network configuration.`
=> fix docker healthcheck

src/main/java/nl/b3p/tailormap/api/FilteringConfig.java
=> [HTM-66] Add FilterRegistrationBean to handle proxy headers

src/main/java/nl/b3p/tailormap/api/health/TailormapHealthIndicator.java, src/main/resources/application.properties, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorEnabledIntegrationTest.java, src/test/resources/application.properties
As a followup on #7 
This HealthIndicator can be augmented when necessary.
resolves HTM-61
=> [HTM-61] Add a healthcheck to obtain Tailormap versions from the database and environment

.github/workflows/ubuntu-maven.yml, pom.xml, src/main/resources/model.yaml, src/main/resources/tailormap-api.yaml
=> [HTM-67] Generate OpenAPI model Java classes

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/controller/VersionController.java, src/main/resources/application.properties, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java, src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorEnabledIntegrationTest.java, src/test/resources/application.properties
- read properties from single source
- fix test coverage reporting
- fix TailormapHealthIndicatorEnabledIntegrationTest
blocks #18
=> Improve integration testing

src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/repository/ApplicationRepository.java, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/TailormapApiApplicationTests.java, src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/AppControllerTest.java, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java, src/test/java/nl/b3p/tailormap/api/repository/ApplicationRepositoryIntegrationTest.java
=> [HTM-68] `app` endpoint

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/resources/model.yaml, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerTest.java
also fix bounds use in some places of the api
resolves HTM-69
=> [HTM-69] Add `map/{appid}` endpoint

src/main/java/nl/b3p/tailormap/api/controller/LayersController.java, src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayersControllerTest.java
initial stub implementation to retrieve layers for an application
resolves HTM-71
=> [HTM-71] Add LayersController for layers/{appid}

src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
only returns a dummy component for now
resolves HTM-70
=> [HTM-70] initial components endpoint

.github/workflows/cleanup_and_maintainance.yml
- policy for untagged image cleanup
- stale PR policy
=> Maintainance workflow

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/resources/model.yaml, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/repository/MetadataRepositoryTest.java
=> [HTM-123] Serve WMTS capabilities document to viewer

.github/workflows/owasp-dependency-check.yml, .github/workflows/trivy.yml, pom.xml
=> Set-up Trivy security scanner

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/LayersController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/java/nl/b3p/tailormap/api/repository/ApplicationRepository.java, src/main/java/nl/b3p/tailormap/api/security/AuthUtil.java, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/TestSecurityConfig.java, src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java
=> [HTM-206] Check login required on application

src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/LayersController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
giving the application id a primary position in the url
see also https://github.com/B3Partners/tailormap-viewer/pull/43 (frontend)
=> [HTM-205] Change API url design

src/main/java/nl/b3p/tailormap/api/repository/UserRepository.java, src/main/java/nl/b3p/tailormap/api/security/AuthUtil.java, src/main/java/nl/b3p/tailormap/api/security/SecurityConfig.java, src/main/java/nl/b3p/tailormap/api/security/StartupAdminAccountCreator.java, src/main/java/nl/b3p/tailormap/api/security/TailormapUserDetails.java, src/main/java/nl/b3p/tailormap/api/security/TailormapUserDetailsService.java, src/main/resources/application.properties, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/security/TailormapUserDetailsServiceTest.java, src/test/java/nl/b3p/tailormap/api/security/TestSecurityConfig.java
- closes HTM-118
- closes HTM-207
- closes HTM-208
=> [HTM-118][HTM-207][HTM-208] Add security

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/LayersController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/java/nl/b3p/tailormap/api/controller/VersionController.java, src/main/java/nl/b3p/tailormap/api/geotools/referencing/ReferencingHelper.java, src/main/java/nl/b3p/tailormap/api/util/ParseUtil.java, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/repository/MetadataRepositoryTest.java, src/test/java/nl/b3p/tailormap/api/util/ParseUtilTest.java
[HTM-251]: https://b3partners.atlassian.net/browse/HTM-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-241]: https://b3partners.atlassian.net/browse/HTM-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-242]: https://b3partners.atlassian.net/browse/HTM-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-243]: https://b3partners.atlassian.net/browse/HTM-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HTM-241][HTM-242][HTM-243][HTM-251] Return actual configuration data from config database in API

src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
=> [HTM-248] Layer tree API tests

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/WFSFeatureSourceHelper.java, src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java, src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/referencing/ReferencingHelperTest.java, src/test/java/nl/b3p/tailormap/api/security/TailormapUserDetailsServiceTest.java
=> Add a testcase for the ReferencingHelper and use ReferencingHelper

.github/workflows/ubuntu-maven.yml, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java, src/main/resources/application.properties, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/resources/application-postgresql.properties, src/test/resources/application.properties
Works for:
resolves HTM-365 (note that for the integration tests to pass HTM 391 / #135  must be resolved)
=> [HTM-365] Paged features response implementation

.github/workflows/ubuntu-maven.yml, build/ci/docker-compose.yml, build/ci/testdata-setup.sh, pom.xml, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/resources/application-postgresql.properties
=> [HTM-391] Set-up integration test data for CI/CD

src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/resources/model.yaml, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
=> [HTM-395] Add a `hasAttributes` member to the API's AppLayer

src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java
=> [HTM-396] Add timing information to the actuator for the relevant endpoints

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
=> [HTM-414] Implement __fid parameter support in FeaturesController

pom.xml
see https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.1
=> Bump mssql-jdbc from 11.2.0.jre11 to 11.2.1.jre11

SECURITY.md, pom.xml, src/main/java/nl/b3p/tailormap/api/JPAConfiguration.java, src/main/java/nl/b3p/tailormap/api/controller/AppController.java, src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/java/nl/b3p/tailormap/api/controller/VersionController.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceFactoryHelper.java, src/main/java/nl/b3p/tailormap/api/health/TailormapHealthIndicator.java, src/main/java/nl/b3p/tailormap/api/repository/ApplicationLayerRepository.java, src/main/java/nl/b3p/tailormap/api/repository/LayerRepository.java, src/main/java/nl/b3p/tailormap/api/repository/LevelRepository.java, src/main/java/nl/b3p/tailormap/api/security/StartupAdminAccountCreator.java, src/main/java/nl/b3p/tailormap/api/security/TailormapUserDetailsService.java, src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java, src/test/java/nl/b3p/tailormap/api/StaticTestData.java, src/test/java/nl/b3p/tailormap/api/TailormapApiApplicationTests.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
Some pretty obvious stuff and some suggestions from IntelliJ
=> ♻️  General code improvements

pom.xml
snakeYAML resolved CVE-2022-38752
=> Bump snakeYAML from 1.31 to 1.32

src/main/resources/statusresponses.yaml, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/model/UniqueValuesResponseTest.java
please see Jira HTM-456 for example use and discussion
resolves HTM-456
=> [WIP] [HTM-456] OpenAPI design for unique values of a layer's feature type attribute

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/VersionController.java, src/main/resources/application.properties, src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorEnabledIntegrationTest.java, src/test/resources/application-postgresql.properties, src/test/resources/application.properties
Add build date/time to version info so we can easily see if the deployment was updated on a snapshot
=> Add build date/time to version info

pom.xml
see https://github.com/B3Partners/tailormap-persistence/pull/47
=> Bump hibernate.version from 5.6.12.Final to 5.6.13.Final

pom.xml
See https://github.com/B3Partners/tailormap-persistence/pull/48
=> Bump hibernate.version from 5.6.13.Final to 5.6.14.Final

src/main/java/nl/b3p/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/nl/b3p/tailormap/api/controller/MapController.java, src/main/java/nl/b3p/tailormap/api/security/AuthorizationService.java, src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerPostgresIntegrationTest.java
=> [HTM-572] Deny feature source access for layers proxied with auth in public app

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/resources/tailormap-api.yaml, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java
Based on #267 
Quick test, not sure what the point was with the `GeometryProcessor.geometryToJson()` code path... Now just WKT
=> [HTM-596] Features: add only geometries parameter

pom.xml
See https://github.com/jeremylong/DependencyCheck/releases/tag/v7.4.4
=> Bump dependency-check-maven.version to 7.4.4

pom.xml
see https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.3
=> Bump mssql-jdbc.version 11.2.2.jre11 ➜ 11.2.3.jre11

pom.xml, src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestDatabase.java, src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java, src/main/resources/openapi/common-schemas-openapi-ignore, src/main/resources/openapi/common-schemas.yaml, src/main/resources/openapi/persistence-schemas.yaml, src/main/resources/openapi/viewer-schemas.yaml, src/test/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelperTest.java
Requires https://github.com/B3Partners/tailormap-viewer/pull/312
=> Add default layer settings, settings per layer and high dpi settings

pom.xml, src/main/java/nl/b3p/tailormap/api/persistence/User.java, src/main/java/nl/b3p/tailormap/api/util/TMPasswordDeserializer.java, src/test/java/nl/b3p/tailormap/api/persistence/UserTest.java, src/test/java/nl/b3p/tailormap/api/util/TMPasswordDeserializerTest.java
see https://b3partners.atlassian.net/wiki/spaces/HT/pages/344031235/tailormap+user+password+handling+options
=> Password encryption for User class when submitted via REST api

pom.xml, src/main/java/nl/b3p/tailormap/api/configuration/ObjectMapperConfiguration.java, src/main/java/nl/b3p/tailormap/api/security/InvalidPasswordException.java, src/main/java/nl/b3p/tailormap/api/util/TMPasswordDeserializer.java, src/main/resources/application.properties, src/test/java/nl/b3p/tailormap/api/persistence/UserTest.java, src/test/java/nl/b3p/tailormap/api/util/TMPasswordDeserializerTest.java, src/test/resources/application.properties
=> [HTM-685] enable strong password validation

pom.xml
see also https://github.com/B3Partners/tailormap-api/security/code-scanning/132
=> Bump snakeyaml.version from 1.33 to 2.0

src/main/java/nl/b3p/tailormap/api/controller/admin/RestExceptionHandler.java, src/main/java/nl/b3p/tailormap/api/persistence/User.java
Would have like to just catch the `InvalidPasswordException` but since that is wrapped up we need to get the cause and act on that
=> Add a RestExceptionHandler to handle invalid passwords and other input

Dockerfile, pom.xml, src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerPostgresIntegrationTest.java
starting with MapControllerPostgresIntegrationTest and AppControllerIntegrationTest
=> Fixup integration tests

src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
Tried to have URL's not hardcoded but that's unfortunately not easy with Spring Boot, because you'd have to check whether a URL maps to an existing file in the bundle.
=> [HTM-720] Add URLs to front controller

pom.xml
=> Bump spring-security.version to 5.8.3

pom.xml, src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerPostgresIntegrationTest.java
resolves HTM-751
_note that here is some leftovers that require authentication, which currently does not work, those are tracked in a separate issue_
=> [HTM-751] Fix GeoServiceProxyControllerPostgresIntegrationTest

pom.xml, src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/test/java/nl/b3p/tailormap/api/controller/MapControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
=> [HTM-757] Restore UniqueValuesControllerPostgresIntegrationTest

codecov.yml, pom.xml, src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/test/java/nl/b3p/tailormap/api/controller/LayerExportControllerIntegrationTest.java
=> [HTM-759] restore LayerExportControllerIntegrationTest

src/main/java/nl/b3p/tailormap/api/repository/events/FeatureSourceEventHandler.java
=> [HTM-758] Load WFS capabilities on add

src/main/java/nl/b3p/tailormap/api/persistence/Group.java, src/main/java/nl/b3p/tailormap/api/persistence/User.java, src/main/java/nl/b3p/tailormap/api/util/Constants.java, src/test/java/nl/b3p/tailormap/api/persistence/GroupTest.java, src/test/java/nl/b3p/tailormap/api/persistence/UserTest.java
resolves HTM-761
see also https://github.com/B3Partners/tailormap-viewer/pull/357
=> [HTM-761] only allow alphanumeric and dash for username or group name

src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/resources/openapi/persistence-schemas.yaml
=> [HTM-744] Add description field to AppTreeLayerNode and AppTreeLevelNode to provide consistency with LayerTreeNode

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/controller/AppRestControllerAdvice.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/security/AuthorizationService.java, src/main/resources/openapi/persistence-schemas.yaml, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerPostgresIntegrationTest.java
I think this is all the places a GeoServiceLayer is retrieved?
=> HTM-768: GeoServiceLayer authorization

src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java, src/main/resources/openapi/persistence-schemas.yaml, src/main/resources/openapi/viewer-schemas.yaml
see also https://github.com/B3Partners/tailormap-viewer/pull/386
=> [HTM-800] Add attribution to AppLayer

pom.xml, src/main/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminController.java, src/main/java/nl/b3p/tailormap/api/repository/events/GeoServiceEventHandler.java, src/test/java/nl/b3p/tailormap/api/StaticTestData.java, src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerReConfiguredPostgresIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminControllerIntegrationTest.java, src/test/resources/application-postgresql.properties, src/test/resources/wms/test_capabilities.xml, src/test/resources/wms/test_capabilities_updated.xml
Do not refresh on @HandleBeforeSave event
=> [HTM-780] Add admin API to refresh geo service capabilities

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
=> [HTM-521] Add some test attribution data

src/main/java/nl/b3p/tailormap/api/persistence/Group.java
see also https://github.com/B3Partners/tailormap-viewer/pull/392
=> [HTM-776] Remove any members from a group before removing the group

src/main/java/nl/b3p/tailormap/api/repository/FeatureSourceRepository.java, src/main/java/nl/b3p/tailormap/api/repository/GeoServiceRepository.java
To make https://github.com/B3Partners/tailormap-viewer/pull/394 a bit more efficient. We could also implement a jsonb query to find references to objects, but that optimization isn't necessary yet.
=> Add getAllExcludingIds call for feature sources and geo services

src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java, src/test/java/nl/b3p/tailormap/api/persistence/GeoServiceTest.java
starting with REQUEST, may need to be expanded
resolves HTM-797
=> [HTM-797] Remove unwanted parameters from a geoservice url before storing

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/util/TMStringUtils.java, src/main/resources/openapi/persistence-schemas.yaml, src/main/resources/openapi/viewer-schemas.yaml
resolves HTM-806, related https://github.com/B3Partners/tailormap-viewer/pull/395
=> [HTM-806] Handle app layer description in the API

src/main/resources/openapi/viewer-api.yaml
One API to rule them all (create/patch/delete), 
resolves HTM-832 and HTM-834
=> [HTM-832][HTM-834] Feature editing API

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/resources/openapi/persistence-schemas.yaml, src/main/resources/openapi/viewer-schemas.yaml, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java
do some cleanup and refactoring
see also https://github.com/B3Partners/tailormap-viewer/pull/414
=> [HTM-843][HTM-859] Refactor Attribute model

src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
Fix 404 when pressing F5 on https://snapshot.tailormap.nl/admin/users/user/tm-admin or https://snapshot.tailormap.nl/admin/groups/group/admin
=> Update front controller URLs

src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java, src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
=> [HTM-879] Discover and produce the primary key of a feature type

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java, src/main/resources/openapi/persistence-schemas.yaml
=> [HTM-885] Handle additionalProperties.connectOptions when connecting to a database

.github/workflows/codeql-analysis.yml
see https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/#2-enable-code-scanning-for-workflows
=> Enable CodeQL analysis of workflow yaml files

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/controller/EditFeatureController.java, src/main/resources/openapi/persistence-schemas.yaml, src/test/java/nl/b3p/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
=> [HTM-897] B - Add and apply `editable` flag to AppLayerSettings

src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
See https://github.com/B3Partners/tailormap-viewer/pull/488
=> Update front controller for single app bundle with viewer and admin

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/controller/EditFeatureController.java, src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java, src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java, src/main/java/nl/b3p/tailormap/api/controller/LayerExportController.java, src/main/java/nl/b3p/tailormap/api/controller/UniqueValuesController.java, src/main/java/nl/b3p/tailormap/api/persistence/Application.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/TMFeatureTypeHelper.java, src/main/resources/openapi/persistence-schemas.yaml, src/test/java/nl/b3p/tailormap/api/controller/EditFeatureControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/persistence/helper/TMFeatureTypeHelperTest.java
Also add hidden attributes to app layer settings
=> [HTM-942]  Add list of read only attributes to feature type and app layer settings

pom.xml, src/test/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminControllerIntegrationTest.java
=> Use version override for okhttp dependencies and upgrade to 5.0.0-alpha.12

.github/workflows/macos-maven.yml, .github/workflows/ubuntu-maven.yml, .github/workflows/windows-maven.yml
see https://github.com/codecov/codecov-action/releases
=> Update Codecov action to v4

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java
=> [HTM-1003] Add `ApplicationName=tailormap-api` to any PostgreSQL connection

src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
required for https://github.com/B3Partners/tailormap-viewer/pull/591
=> [HTM-1043] Add German locale

src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java, src/main/java/nl/b3p/tailormap/api/security/CsrfCookieFilter.java
=> HTM-1070: Fix Spring Boot CSRF problems for SPA

src/main/java/nl/b3p/tailormap/api/controller/LayerExportController.java, src/test/java/nl/b3p/tailormap/api/controller/LayerExportControllerIntegrationTest.java
=> [HTM-669][HTM-1121] Validate fields before sending export request to WFS

.github/workflows/ubuntu-maven.yml
This will only show after merge because this build step only runs on the main branch
resolves HTM-1123
=> [HTM-1123] Fix expected location of SBOM file

src/main/resources/application.properties
=> HTM-1129: fix metrics application label

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java, src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerIntegrationTest.java, src/test/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelperIntegrationTest.java
=> HTM-1133: WMS LegendURL of inherited style is picked as default

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/nl/b3p/tailormap/api/solr/SolrHelper.java, src/main/resources/application.properties, src/main/resources/openapi/persistence-schemas.yaml
=> Removed searchFields and searchDisplayFields from feature type

.github/workflows/cleanup_and_maintainance.yml, .github/workflows/codeql-analysis.yml, .github/workflows/macos-maven.yml, .github/workflows/owasp-dependency-check.yml, .github/workflows/process-test-results.yml, .github/workflows/qa.yml, .github/workflows/release-drafter.yml, .github/workflows/reuse.yml, .github/workflows/trivy.yml, .github/workflows/ubuntu-maven.yml, pom.xml
companion to https://github.com/B3Partners/tailormap-viewer/pull/682
=> HTM-1173: Rename docker images to use the new Tailormap organisation

.github/workflows/ubuntu-maven.yml
[![HTM-1168](https://badgen.net/badge/JIRA/HTM-1168/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1168) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1168: add write permission to update maven site

build/ci/docker-compose.yml
[![HTM-1175](https://badgen.net/badge/JIRA/HTM-1175/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1175) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1175: the Tailormap Data stack was moved to a different repository

SECURITY.md, pom.xml
[![HTM-1194](https://badgen.net/badge/JIRA/HTM-1194/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1194) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1194: Bump to version 11.4.0

pom.xml, src/main/java/org/tailormap/api/configuration/base/FrontController.java, src/main/java/org/tailormap/api/configuration/base/WebMvcConfig.java, src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
[![HTM-1041](https://badgen.net/badge/JIRA/HTM-1041/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1041) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1041]: https://b3partners.atlassian.net/browse/HTM-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1041: fix error prone warnings, restore compiler error levels

.github/workflows/macos-maven.yml, .github/workflows/owasp-dependency-check.yml, .github/workflows/qa.yml, .github/workflows/trivy.yml, .github/workflows/ubuntu-maven.yml, .github/workflows/windows-maven.yml
[![HTM-1029](https://badgen.net/badge/JIRA/HTM-1029/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1029) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1029: Update Maven runtime in workflows

.github/workflows/trivy.yml
[![HTM-1208](https://badgen.net/badge/JIRA/HTM-1208/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1208) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
using https://github.com/yogeshlonkar/trivy-cache-action
[HTM-1208]: https://b3partners.atlassian.net/browse/HTM-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1208: Add caching for Trivy

pom.xml
[![HTM-1214](https://badgen.net/badge/JIRA/HTM-1214/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1214) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
- Bump spring-hateoas.version from 2.3.2 to 2.3.3
- Bump flyway.version from 10.17.2 to 10.18.0
- Bump spring-data-bom.version from 2024.0.3 to 2024.0.4
- Bump micrometer.version from 1.13.3 to 1.13.4
=> HTM-1214: dependency updates

.github/workflows/macos-maven.yml, .github/workflows/ubuntu-maven.yml, .github/workflows/windows-maven.yml
[![HTM-1215](https://badgen.net/badge/JIRA/HTM-1215/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1215) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1215]: https://b3partners.atlassian.net/browse/HTM-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1215: update Codecov config to upload tests

src/main/java/org/tailormap/api/geotools/featuresources/WFSFeatureSourceHelper.java, src/main/java/org/tailormap/api/geotools/wfs/SimpleWFSHelper.java, src/main/java/org/tailormap/api/persistence/GeoService.java
[![HTM-1002](https://badgen.net/badge/JIRA/HTM-1002/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1002) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1002: Sanitize WFS url params

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
[![HTM-1220](https://badgen.net/badge/JIRA/HTM-1220/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Provides the interface/API to:
- list (optionally filtered by type)
- retrieve all details for a specific task
- start
- stop
- delete
tasks.
The methods in the interface will need to be further implemented using the `spring-boot-starter-quartz` module: https://docs.spring.io/spring-boot/reference/io/quartz.html
[HTM-1220]: https://b3partners.atlassian.net/browse/HTM-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> HTM-1220: initial (scheduled/background) task controller to determine the API

src/main/java/org/tailormap/api/controller/FeaturesController.java, src/main/java/org/tailormap/api/util/Constants.java, src/main/resources/application.properties, src/test/resources/application.properties
[![HTM-1195](https://badgen.net/badge/JIRA/HTM-1195/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1195) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
increase default maximum number of features to 30 and make it configurable per instance using a property
[HTM-1195]: https://b3partners.atlassian.net/browse/HTM-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1195: increase default maximum number of features

src/main/resources/application.properties
[![HTM-1227](https://badgen.net/badge/JIRA/HTM-1227/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1227) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
see ticket for documentation and background
also expose the sbom endpoint
[HTM-1227]: https://b3partners.atlassian.net/browse/HTM-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1227: expose the quartz actuator endpoint

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/controller/AppRestControllerAdvice.java, src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/org/tailormap/api/security/AuthorizationService.java, src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/TestUrls.java, src/test/java/org/tailormap/api/controller/UniqueValuesControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
[![HTM-952](https://badgen.net/badge/JIRA/HTM-952/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-952) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-952]: https://b3partners.atlassian.net/browse/HTM-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-952: Fix regression allowing access to proxied-with-auth layers in public apps (with or without login)

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
[![HTM-816](https://badgen.net/badge/JIRA/HTM-816/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-816) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
counterpart to: https://github.com/Tailormap/tailormap-viewer/pull/725
[HTM-816]: https://b3partners.atlassian.net/browse/HTM-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-816: Replaced HTML attribution by Markdown attribution

pom.xml
[![HTM-1252](https://badgen.net/badge/JIRA/HTM-1252/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1252) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1252: Upgrade Spring Data to 2024.0.5

pom.xml
[![HTM-1274](https://badgen.net/badge/JIRA/HTM-1274/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1274) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1274]: https://b3partners.atlassian.net/browse/HTM-1274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1274: Bump jetty.version to 10.0.24

pom.xml
[![HTM-1278](https://badgen.net/badge/JIRA/HTM-1278/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1278) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1278: Update org.junit:junit-bom from v5.11.2 to v5.11.3

src/main/java/org/tailormap/api/controller/LayerExportController.java, src/main/java/org/tailormap/api/geotools/wfs/SimpleWFSHelper.java, src/main/java/org/tailormap/api/geotools/wfs/SimpleWFSLayerDescription.java, src/main/java/org/tailormap/api/persistence/helper/GeoServiceHelper.java, src/main/java/org/tailormap/api/repository/validation/FeatureSourceValidator.java, src/main/java/org/tailormap/api/repository/validation/GeoServiceValidator.java, src/main/java/org/tailormap/api/security/AuditInterceptor.java, src/main/java/org/tailormap/api/security/CsrfCookieFilter.java, src/main/java/org/tailormap/api/security/OIDCRepository.java, src/main/java/org/tailormap/api/security/TailormapUserDetails.java, src/main/java/org/tailormap/api/security/TailormapUserDetailsService.java, src/test/java/org/tailormap/api/controller/admin/PersistentJsonArrayPropertyIntegrationTest.java, src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java
[![HTM-1283](https://badgen.net/badge/JIRA/HTM-1283/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1283) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1283]: https://b3partners.atlassian.net/browse/HTM-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1283: Apply general code maturity recommendations

src/test/java/org/tailormap/api/controller/admin/UnreachableSolrAdminControllerIntegrationTest.java
[![HTM-1265](https://badgen.net/badge/JIRA/HTM-1265/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1265]: https://b3partners.atlassian.net/browse/HTM-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1284: Add the unhappy path testcases for a misconfigured Solr URL

src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java, src/test/java/org/tailormap/api/repository/events/SearchIndexEventHandlerIntegrationTest.java
[![HTM-1258](https://badgen.net/badge/JIRA/HTM-1258/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1258) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1258]: https://b3partners.atlassian.net/browse/HTM-1258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1258: Allow storing only one task per search index

README.md, pom.xml, src/test/java/org/tailormap/api/geotools/processing/GeometryProcessorTest.java, src/test/java/org/tailormap/api/repository/ApplicationRepositoryIntegrationTest.java, src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java
[![HTM-1293](https://badgen.net/badge/JIRA/HTM-1293/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1293) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
also cleanup and check used dependencies
=> HTM-1293: Use Hamcrest 3 test utilities

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/scheduling/FailingPocTask.java, src/main/java/org/tailormap/api/scheduling/IndexTask.java, src/main/java/org/tailormap/api/scheduling/PocTask.java, src/main/java/org/tailormap/api/scheduling/Task.java
[![HTM-1295](https://badgen.net/badge/JIRA/HTM-1295/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1295]: https://b3partners.atlassian.net/browse/HTM-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1295: add last result to api response at api/admin/tasks

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java, src/main/java/org/tailormap/api/scheduling/Task.java, src/main/java/org/tailormap/api/scheduling/TaskType.java, src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
[![HTM-1315](https://badgen.net/badge/JIRA/HTM-1315/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1315) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[![HTM-1315](https://badgen.net/badge/JIRA/HTM-1316/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1316)
[HTM-1315]: https://b3partners.atlassian.net/browse/HTM-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1315]: https://b3partners.atlassian.net/browse/HTM-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> HTM-1315 | HTM-1316: Implement startTask() and stopTask() methods

src/main/java/org/tailormap/api/solr/SolrHelper.java
[![HTM-1313](https://badgen.net/badge/JIRA/HTM-1313/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1313) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1313]: https://b3partners.atlassian.net/browse/HTM-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1313: prevent submitting bogus document to Solr

src/main/java/org/tailormap/api/solr/SolrHelper.java, src/test/java/org/tailormap/api/controller/admin/UnreachableSolrAdminControllerIntegrationTest.java
[![HTM-1321](https://badgen.net/badge/JIRA/HTM-1321/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1321) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1321]: https://b3partners.atlassian.net/browse/HTM-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1321: Make Solr schema creation more robust

src/main/java/org/tailormap/api/solr/SolrHelper.java, src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
[![HTM-1091](https://badgen.net/badge/JIRA/HTM-1091/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1091) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1091]: https://b3partners.atlassian.net/browse/HTM-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1091: Enable bbox filtering for Solr search

pom.xml
see https://github.com/quartz-scheduler/quartz/releases/tag/v2.4.0
=> Bump quartz.version from 2.3.2 to 2.4.0

.github/workflows/ubuntu-maven.yml, pom.xml
[![HTM-1242](https://badgen.net/badge/JIRA/HTM-1242/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1242]: https://b3partners.atlassian.net/browse/HTM-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1242: remove arm64 building from API

pom.xml
[![HTM-1333](https://badgen.net/badge/JIRA/HTM-1333/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Use Spring Data REST BOM 2024.0.6 with version 4.3.6 which includes the fix for [issue 2425](https://github.com/spring-projects/spring-data-rest/issues/2425).
[HTM-1333]: https://b3partners.atlassian.net/browse/HTM-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1333: Fix error saving a user who has group memberships

pom.xml
[![HTM-1330](https://badgen.net/badge/JIRA/HTM-1330/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1330) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1330]: https://b3partners.atlassian.net/browse/HTM-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1330: Upgrade Spring Boot 3.3.5 ⇥ 3.3.6

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/repository/SearchIndexRepository.java, src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
[![HTM-1331](https://badgen.net/badge/JIRA/HTM-1331/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1331]: https://b3partners.atlassian.net/browse/HTM-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1331: Make sure we cleanup the schedule when a task is deleted

src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
=> Fix error persisting detached entity

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java, src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
[![HTM-1348](https://badgen.net/badge/JIRA/HTM-1348/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1348) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Update the JobDetail of a Job in the scheduler when updating task. This means the priority and description also get updated.
[HTM-1348]: https://b3partners.atlassian.net/browse/HTM-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1348: Update JobDetail when updating a task

pom.xml
[![HTM-1349](https://badgen.net/badge/JIRA/HTM-1349/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1349) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1349: Consolidate logging libraries and ban old junit

pom.xml, src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java, src/main/java/org/tailormap/api/scheduling/TaskManagerService.java, src/test/java/org/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java, src/test/resources/application.properties
[![HTM-1073](https://badgen.net/badge/JIRA/HTM-1073/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1073) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1073]: https://b3partners.atlassian.net/browse/HTM-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1073: Start a manual indexing job on the scheduler instead of in the request thread

src/main/java/org/tailormap/api/persistence/SearchIndex.java
[![HTM-1351](https://badgen.net/badge/JIRA/HTM-1351/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1351) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1351]: https://b3partners.atlassian.net/browse/HTM-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1351: Add EntityListeners annotation to enable sending SSE when updates occur

pom.xml
[![HTM-1358](https://badgen.net/badge/JIRA/HTM-1358/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1358: Remove unused commons-codec

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
forgot some things in https://github.com/Tailormap/tailormap-api/pull/1077
=> Add forgotten files of #1077

src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java, src/test/java/org/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java
[![HTM-1362](https://badgen.net/badge/JIRA/HTM-1362/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1362) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1362]: https://b3partners.atlassian.net/browse/HTM-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1362: fix Inconsistency in naming of the returned task

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/scheduling/IndexTask.java, src/main/java/org/tailormap/api/scheduling/PocTask.java, src/main/java/org/tailormap/api/scheduling/Task.java, src/main/java/org/tailormap/api/solr/SolrHelper.java, src/main/resources/openapi/admin-schemas.yaml
[![HTM-1359](https://badgen.net/badge/JIRA/HTM-1359/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1359)
[![HTM-1360](https://badgen.net/badge/JIRA/HTM-1360/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1360) 
closes #1067
[HTM-1359]: https://b3partners.atlassian.net/browse/HTM-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1360]: https://b3partners.atlassian.net/browse/HTM-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1359 | HTM-1360: Scheduled tasks should emit events on progress

src/main/resources/openapi/viewer-api.yaml
[![HTM-1372](https://badgen.net/badge/JIRA/HTM-1372/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1372]: https://b3partners.atlassian.net/browse/HTM-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1372: add operationIds for the page endpoints

src/main/resources/openapi/viewer-api.yaml, src/main/resources/openapi/viewer-schemas.yaml
[![HTM-1375](https://badgen.net/badge/JIRA/HTM-1375/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
fixes:
Warning: Validation 'minLength' has no effect on schema 'array'. Ignoring!
Warning: Validation 'minLength' has no effect on schema 'array'. Ignoring!
Warning: Validation 'minLength' has no effect on schema 'array'. Ignoring!
Warning: Validation 'minLength' has no effect on schema 'array'. Ignoring!
Warning: Validation 'minLength' has no effect on schema 'array'. Ignoring!
Warning: Validation 'minLength' has no …
=> HTM-1375: fix OpenAPI errors and warnings

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
see https://basemap.at/highdpi/ and https://github.com/openlayers/openlayers/pull/16463#issue-2739879777
=> CI: update Austria basemap capabilities url

.github/workflows/ubuntu-maven.yml, pom.xml
[![HTM-1379](https://badgen.net/badge/JIRA/HTM-1379/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1379) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
=> HTM-1379: remove dependency track buildsteps in tailormap-api

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
[![HTM-1389](https://badgen.net/badge/JIRA/HTM-1389/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1389) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
relates to https://github.com/Tailormap/tailormap-viewer/pull/787
[HTM-1389]: https://b3partners.atlassian.net/browse/HTM-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1389: add test data for search filtering

src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java, src/main/java/org/tailormap/api/scheduling/IndexTask.java, src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java, src/main/java/org/tailormap/api/scheduling/PocTask.java, src/main/java/org/tailormap/api/scheduling/Task.java
[![HTM-1398](https://badgen.net/badge/JIRA/HTM-1398/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1398]: https://b3partners.atlassian.net/browse/HTM-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1398: refactor task keys

src/main/java/org/tailormap/api/persistence/listener/EntityEventPublisher.java
..., but not when there arent't any subscribers
=> Also send SSE events without request context

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java, src/main/java/org/tailormap/api/scheduling/PocTask.java, src/main/java/org/tailormap/api/solr/SolrHelper.java, src/main/resources/openapi/admin-schemas.yaml
[![HTM-1402](https://badgen.net/badge/JIRA/HTM-1402/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1402) 
[![HTM-1402](https://badgen.net/badge/JIRA/HTM-1403/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1403) 
[<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
companion to https://github.com/Tailormap/tailormap-viewer/pull/793, part of https://b3partners.atlassian.net/browse/HTM-1401
[HTM-1402]: https://b3partners.atlassian.net/browse/HTM-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1401 | HTM-1402 | HTM-1403: Update task-progress event to have optional map of task data and use it to transmit eg. indexId

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/admin/FeatureSourceAdminControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java, src/test/resources/application.properties
[![HTM-1405](https://badgen.net/badge/JIRA/HTM-1405/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1405) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
needs https://github.com/Tailormap/tailormap-data/pull/22
[HTM-1405]: https://b3partners.atlassian.net/browse/HTM-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1405: Add kadastrale aanduiding layer and search index in default app

src/main/java/org/tailormap/api/persistence/Group.java, src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java, src/main/java/org/tailormap/api/security/TailormapUserDetails.java, src/main/resources/db/migration/V14__group_alias_for.sql
[![HTM-1298](https://badgen.net/badge/JIRA/HTM-1298/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1298) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1298]: https://b3partners.atlassian.net/browse/HTM-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1298: Add aliasForGroup to grant an additional authority when user is member of a (SSO-)group

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/persistence/Group.java, src/main/java/org/tailormap/api/persistence/User.java, src/main/java/org/tailormap/api/persistence/helper/AdminAdditionalPropertyHelper.java, src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java, src/main/java/org/tailormap/api/security/AuthenticationEventsLogger.java, src/main/java/org/tailormap/api/security/OIDCAuthenticationEventsHandler.java, src/main/resources/application.properties, src/main/resources/db/migration/V15__built_in_group_defaults.sql
[![HTM-1410](https://badgen.net/badge/JIRA/HTM-1410/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1410]: https://b3partners.atlassian.net/browse/HTM-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1410/HTM-1411: Add OIDC information

build/ci/docker-compose.yml
[![HTM-1421](https://badgen.net/badge/JIRA/HTM-1421/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1421) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
see https://github.com/Tailormap/tailormap-data/pull/26
[HTM-1421]: https://b3partners.atlassian.net/browse/HTM-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1421: Upgrade Solr from 9.7.0 to 9.8.0

pom.xml, src/main/java/org/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java
see https://github.com/geotools/geotools/releases/tag/32.2
=> Bump geotools.version from 32.1 to 32.2

src/main/java/org/tailormap/api/controller/LayerExportController.java
[![HTM-1425](https://badgen.net/badge/JIRA/HTM-1425/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1425) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1425]: https://b3partners.atlassian.net/browse/HTM-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1425: Use a Set instead of a List to prevent requesting duplicate properties

src/main/java/org/tailormap/api/persistence/projections/TMFeatureSourceSummary.java
[![HTM-1431](https://badgen.net/badge/JIRA/HTM-1431/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1431) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
…model to show warnings in catalog tree
[HTM-1431]: https://b3partners.atlassian.net/browse/HTM-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1431: Add defaultGeometryColumn and primaryKeyAttribute in feature type summary

README.md, build/ci/docker-compose.yml, pom.xml, src/main/java/org/tailormap/api/drawing/DrawingService.java, src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
[![HTM-1452](https://badgen.net/badge/JIRA/HTM-1452/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1452) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
and some other small changes
[HTM-1452]: https://b3partners.atlassian.net/browse/HTM-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1452: sort drawings by creation date

src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
Bugfix: make comparison with web mercator crs string null safe in isWebMercatorAvailable()
=> make comparison with web mercator crs string null safe 

src/main/java/org/tailormap/api/controller/AppRestControllerAdvice.java, src/main/java/org/tailormap/api/controller/PageController.java, src/main/java/org/tailormap/api/controller/ViewerController.java, src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/org/tailormap/api/security/AuthorizationService.java
use a noun/permission/action pattern instead of the permission/noun/action pattern, which is more like natural language.
=> Refactor the method names to be more natural language like

src/main/java/org/tailormap/api/drawing/DrawingService.java, src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
[![HTM-1469](https://badgen.net/badge/JIRA/HTM-1469/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1469) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1469]: https://b3partners.atlassian.net/browse/HTM-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1469: fix DrawingController does not return Feature id as part of GeoJSON

pom.xml
[![HTM-1447](https://badgen.net/badge/JIRA/HTM-1447/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1447) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
_this PR will fail until after GeoTools 33.0 has been released, see https://github.com/geotools/geotools/tags_
[HTM-1447]: https://b3partners.atlassian.net/browse/HTM-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1447: Upgrade GeoTools to 33.0

src/main/java/org/tailormap/api/drawing/DrawingService.java
[![EK-39](https://badgen.net/badge/JIRA/EK-39/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-39) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-39]: https://b3partners.atlassian.net/browse/EK-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EK-39: Fetch list of all drawings if a user has rights

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java, src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java, src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
[![HTM-1500](https://badgen.net/badge/JIRA/HTM-1500/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1500) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1500]: https://b3partners.atlassian.net/browse/HTM-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1500: Add 3D Tiles functionality to proxy controller

build/ci/docker-compose.yml, pom.xml, src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/java/org/tailormap/api/persistence/Application.java, src/main/resources/openapi/common-schemas.yaml, src/main/resources/openapi/persistence-schemas.yaml, src/main/resources/openapi/viewer-api.yaml, src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
[![HTM-1510](https://badgen.net/badge/JIRA/HTM-1510/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1510) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[![HTM-1511](https://badgen.net/badge/JIRA/HTM-1511/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1511)
[HTM-1510]: https://b3partners.atlassian.net/browse/HTM-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1511]: https://b3partners.atlassian.net/browse/HTM-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> HTM-1510 | HTM-1511: API and testdata for storing and retrieving filterGroups 

src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
[![HTM-1483](https://badgen.net/badge/JIRA/HTM-1483/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1483) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1483]: https://b3partners.atlassian.net/browse/HTM-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1483: Check if web mercator is available for WMTS hiDpiSubstituteLayer.

src/main/resources/openapi/common-schemas.yaml
[![HTM-1520](https://badgen.net/badge/JIRA/HTM-1520/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1520) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[![HTM-1522](https://badgen.net/badge/JIRA/HTM-1522/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1522)
This will enable Naktuinbouw to use forms with automatically filled/updated usenrname on selected text fields and updated date/timestamp on date respectively timestamp form fields.
[HTM-1520]: https://b3partners.atlassian.net/browse/HTM-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> HTM-1520 | HTM-1522: Add autofill options for selected text and date/time fields in forms to API/data model

src/main/java/org/tailormap/api/controller/LayerExportController.java
[![HTM-1582](https://badgen.net/badge/JIRA/HTM-1582/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1582) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1582]: https://b3partners.atlassian.net/browse/HTM-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1582: fix failing downloads because entity resolution is disallowed

src/main/resources/openapi/common-schemas.yaml
[![HTM-1583](https://badgen.net/badge/JIRA/HTM-1583/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1583) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1583]: https://b3partners.atlassian.net/browse/HTM-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1583: Extend slider filter model with input mode

pom.xml, src/main/resources/application.properties
and setup sending logs
see https://github.com/getsentry/sentry-java/releases/tag/8.16.0
=> Bump `sentry.version` from 8.15.1 to 8.16.0

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java, src/main/resources/openapi/common-schemas.yaml
[![HTM-1592](https://badgen.net/badge/JIRA/HTM-1592/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1592) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1592]: https://b3partners.atlassian.net/browse/HTM-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1592: Extend datamodel to include dropdown list filters

src/test/java/org/tailormap/api/controller/admin/UniqueValuesAdminControllerIntegrationTest.java
[![HTM-1593](https://badgen.net/badge/JIRA/HTM-1593/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1593) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
see https://github.com/Tailormap/tailormap-api/pull/1292#discussion_r2218696184
Use repositories to lookup by name instead of assuming a static featuretype id, also add a testcase with filter applied.
[HTM-1593]: https://b3partners.atlassian.net/browse/HTM-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1593: fix faulty testcase

.github/workflows/codeql.yml, .github/workflows/macos-maven.yml, .github/workflows/owasp-dependency-check.yml, .github/workflows/qa.yml, .github/workflows/trivy.yml, .github/workflows/ubuntu-maven.yml
see https://github.com/apache/maven/releases/tag/maven-3.9.11 and https://github.com/apache/maven/releases/tag/maven-3.9.10
=> Update Maven version from 3.9.9 to 3.9.11

src/main/java/org/tailormap/api/controller/AppRestControllerAdvice.java, src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java, src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java, src/main/java/org/tailormap/api/security/AuthorisationService.java, src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
[![HTM-1586](https://badgen.net/badge/JIRA/HTM-1586/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1586]: https://b3partners.atlassian.net/browse/HTM-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1586: Allow proxying layers from secured services for authenticated users

src/main/java/org/tailormap/api/controller/IngestMetricsController.java, src/main/java/org/tailormap/api/controller/ViewerController.java, src/main/java/org/tailormap/api/prometheus/TagNames.java, src/test/java/org/tailormap/api/controller/ViewerControllerWithActuatorIntegrationTest.java
[![HTM-1605](https://badgen.net/badge/JIRA/HTM-1605/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1605) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Copy part of #1330 to introduce a Micrometer counter that increments each time an application is requested.
Also use constants for the tag names
[HTM-1605]: https://b3partners.atlassian.net/browse/HTM-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1605: Add code to generate application request metric in ViewerController

build/ci/compose-config-files/prometheus.yaml, build/ci/docker-compose.yml, pom.xml, src/main/java/org/tailormap/api/prometheus/PrometheusResultProcessor.java, src/main/resources/application.properties, src/test/java/org/tailormap/api/PrometheusIntegrationTest.java, src/test/java/org/tailormap/api/controller/IngestMetricsControllerIntegrationTest.java, src/test/java/org/tailormap/api/prometheus/PrometheusResultProcessorTest.java
[![HTM-1606](https://badgen.net/badge/JIRA/HTM-1606/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1606) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
picked and based from #1330
[HTM-1606]: https://b3partners.atlassian.net/browse/HTM-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1606: Update CI stack to include a configured prometheus service

.github/workflows/copilot-setup-steps.yml, build/ci/docker-compose.yml, build/ci/prometheus-backfill.sh, build/ci/testdata-setup.sh, pom.xml, src/main/java/org/tailormap/api/configuration/RestTemplateConfig.java, src/main/java/org/tailormap/api/prometheus/PrometheusService.java, src/test/java/org/tailormap/api/PrometheusIntegrationTest.java, src/test/java/org/tailormap/api/prometheus/PrometheusServiceIntegrationTest.java, src/test/java/org/tailormap/api/prometheus/PrometheusServiceUnhappyIntegrationTest.java, src/test/resources/application-postgresql.properties
[![HTM-1601](https://badgen.net/badge/JIRA/HTM-1601/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1601) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)  [![HTM-1601](https://badgen.net/badge/JIRA/HTM-1613/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1613) 
Also adds some metrics for backfilling: [HTM-1613](https://b3partners.atlassian.net/browse/HTM-1613)
[HTM-1601]: https://b3partners.atlassian.net/browse/HTM-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1613]: …
=> HTM-1601: Add a Spring service for any interactions with the Prometheus REST API

src/main/java/org/tailormap/api/controller/ViewerController.java, src/main/java/org/tailormap/api/persistence/Application.java, src/main/java/org/tailormap/api/persistence/helper/ViewerHelper.java, src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
[![HTM-1645](https://badgen.net/badge/JIRA/HTM-1645/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1645) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Make sure that filters are only available for layers that the user can view
[HTM-1645]: https://b3partners.atlassian.net/browse/HTM-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1645: Apply layer access rules to filters

src/main/java/org/tailormap/api/security/TailormapUserDetails.java
[![HTM-1657](https://badgen.net/badge/JIRA/HTM-1657/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1657) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1657]: https://b3partners.atlassian.net/browse/HTM-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1657: Fix login problems for user where additional_properties is null

src/main/java/org/tailormap/api/controller/UserController.java, src/main/java/org/tailormap/api/drawing/DrawingService.java, src/main/java/org/tailormap/api/repository/GroupRepository.java, src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java, src/main/java/org/tailormap/api/security/TailormapAdditionalProperty.java, src/main/java/org/tailormap/api/security/TailormapOidcUser.java, src/main/java/org/tailormap/api/security/TailormapOidcUserService.java, src/main/java/org/tailormap/api/security/TailormapUserDetails.java, src/main/java/org/tailormap/api/security/TailormapUserDetailsImpl.java, src/main/java/org/tailormap/api/security/TailormapUserDetailsService.java, src/test/java/org/tailormap/api/controller/UserControllerIntegrationTest.java
[![HTM-1680](https://badgen.net/badge/JIRA/HTM-1680/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1680) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Requires update for backends using spring-session-jdbc
[HTM-1680]: https://b3partners.atlassian.net/browse/HTM-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTM-1680: Fix  drawing admin / read-all authorizations
