.github/workflows/macos-maven.yml
.github/workflows/ubuntu-maven.yml
.github/workflows/windows-maven.yml
Dockerfile
README.md
pom.xml
src/main/java/nl/b3p/tailormap/api/JPAConfiguration.java
src/main/java/nl/b3p/tailormap/api/controller/AppController.java
src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
src/main/java/nl/b3p/tailormap/api/repository/MetadataRepository.java
src/main/resources/application.properties
src/main/resources/static/index.html
src/main/resources/tailormap-api.yaml
src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java
src/test/java/nl/b3p/tailormap/api/TailormapApiApplicationTests.java
src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/repository/MetadataRepositoryIntegrationTest.java
src/test/resources/application.properties

Uses the original `org.tailormap:viewer-config-persistence` module for now and only for a preconfigured PostgreSQL config database.
resolves HTM-38

[HTM-38] Add database connectivity for Tailormap API

---

src/main/resources/model.yaml

note that the CRS of Bounds is now optional and a string to avoid a circular reference

[HTM-11] Make the CoordinateReferenceSystem also carry the PROJ4 definition as well as (optional) area of validity

---

src/main/java/nl/b3p/tailormap/api/repository/MetadataRepository.java
src/test/java/nl/b3p/tailormap/api/repository/ApplicationRepositoryTest.java
src/test/java/nl/b3p/tailormap/api/repository/MetadataRepositoryTest.java

It's not necessary to start the whole Spring Boot application for JPA tests, we just need an initialised database.

Optimize JPA tests by not initializing the whole application

---

src/main/java/nl/b3p/tailormap/api/controller/AppController.java
src/main/java/nl/b3p/tailormap/api/exception/TailormapConfigurationException.java
src/main/java/nl/b3p/tailormap/api/exception/TailormapException.java
src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java

`/app` endpoint returned HTTP 200 with HTTP 500 error payload on misconfiguration, will now return 500

Return proper HTTP status on configuration error

---

src/test/java/nl/b3p/tailormap/api/ValidateGeoToolsInArtifactIntegrationTest.java

Prevent GeoTools version and factory conflicts

Check if there is only one `gt-main` and only one `gt-epsg` jar in the runnable jar

---

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
src/main/resources/model.yaml
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java

which can be used for highlighting. Note that the option `simplify=true` should  be used to save bandwidth and cpu
resolves HTM-258

[HTM-258] Add geometry field to Feature

---

pom.xml

Bump/override jackson-bom.version from 2.13.1 -> 2.13.2

---

Dockerfile
src/main/resources/application.properties

this port does not have to be publicly exposed, maybe needs a change in the traefik config and nginx reverse proxy config of https://github.com/B3Partners/tailormap-viewer to make it accessible outside the container stack if that is needed at all - I think it would be better to connect any monitoring application into the `tailormap-viewer` network

[HTM-309] Change management port to 9090

---

src/main/java/nl/b3p/tailormap/api/controller/MapController.java
src/main/resources/model.yaml

HTM-48
Note that this includes a recursive method to find a service layer by name which should be implemented in an optimized way instead, but that is tracked in HTM-327.
see https://github.com/B3Partners/tailormap-admin/pull/92

Return hidpi options for services and layers

---

pom.xml

by increasing both the number of times a check for a running application is done as well as the interval between checks

Try to resolve integration test failures on merged branch integration test build

---

pom.xml
src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
src/main/resources/application.properties
src/main/resources/static/index.html
src/main/resources/tailormap-api.yaml
src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
src/test/resources/application-postgresql.properties
src/test/resources/application.properties

resolves HTM-397
calling `/api/version` will produce something like 
```json 
{"version":"0.1-SNAPSHOT",
"commitSha":"05b3fce1e2991972642dc8a656d013c455e889ea",
"apiVersion":"v1","databaseversion":"47"}
```

[HTM-397] Add git commit id to version info

---

pom.xml

see also https://github.com/B3Partners/tailormap-persistence/pull/4
Bumps `hibernate.version` from 5.6.9.Final to 5.6.10.Final.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/hibernate/hibernate-orm/blob/5.6.10/changelog.txt">hibernate-core's changelog</a>.</em></p>
<blockquote>
<h2>Changes in 5.6.10.Final (July 07, 2022)</h2>
<p><a href="https://hibernate.atlassian.net/projects/HHH/versions/32076">https://hibernate.atlassian.net/projects/HHH/versions/32076</a></p>
<p>** Bug
* [HHH-15281] - INSERTs/UPDATEs no longer executed as JDBC Batch statements if hibernate.temp.use_jdbc_metadata_defaults is set to false
* [HHH-15218] - <a href="https://github.com/OptimisticLocking"><code>@​OptimisticLocking</code></a>(DIRTY) leads to wrong query during delete …

Bump hibernate.version from 5.6.9.Final to 5.6.10.Final

---

src/main/java/nl/b3p/tailormap/api/controller/MapController.java
src/main/java/nl/b3p/tailormap/api/repository/ApplicationLayerRepository.java
src/main/java/nl/b3p/tailormap/api/repository/ApplicationRepository.java
src/main/java/nl/b3p/tailormap/api/repository/LayerRepository.java
src/main/java/nl/b3p/tailormap/api/repository/LevelRepository.java
src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java

HTM-272
HTM-327
Combined PR as the authorization commit builds on top of the layer title commit. The layer title commit should be self-explanatory, so some details on the authorization commit:
To avoid the `n+1` issue with ORMs, this commit uses `EntityGraph`s to fetch most necessary components in one go, exchanging latency for bandwidth use. The SQL queries are visualised here to the best of my abilities:
```mermaid
flowchart TD
%% query 1
Application -->|findWithGeoservicesById| ApplicationLayer
ApplicationLayer  -->|findWithGeoservicesById| GeoService
%% query 2
Level -->|findByLevelTree| Level
%% query 3
Level -->|findWithAuthorizationDataByIdIn| ApplicationLayer
ApplicationLayer -->|findWithAuthorizationDataByIdIn| GeoService
%% query 4
%% just fetches ApplicationLayers that have not …
```

[HTM-272][HTM-327] Add support for proper layer titles, authorisation

---

pom.xml

Bumps `hibernate.version` from 5.6.10.Final to 5.6.11.Final.
Updates `hibernate-core` from 5.6.10.Final to 5.6.11.Final
- [Release notes](https://github.com/hibernate/hibernate-orm/releases)
- [Changelog](https://github.com/hibernate/hibernate-orm/blob/5.6.11/changelog.txt)
- [Commits](hibernate/hibernate-orm@5.6.10...5.6.11)
Updates `hibernate-entitymanager` from 5.6.10.Final to 5.6.11.Final
- [Release notes](https://github.com/hibernate/hibernate-orm/releases)
- [Changelog](https://github.com/hibernate/hibernate-orm/blob/5.6.11/changelog.txt)
- [Commits](hibernate/hibernate-orm@5.6.10...5.6.11)
related https://github.com/B3Partners/tailormap-persistence/pull/24

Bump hibernate.version from 5.6.10.Final to 5.6.11.Final

---

src/main/java/nl/b3p/tailormap/api/controller/MapController.java
src/main/resources/model.yaml

this will show like:
```json
{
"id": 9,
"layerName": "sqlserver:wegdeel",
"title": "wegdeel",
"serviceId": 6,
"visible": true,
"minScale": 0.0,
"maxScale": 5000.0,
"legendImageUrl": null,
"hiDpiMode": null,
"hiDpiSubstituteLayer": null,
"hasAttributes": true
},
{
"id": 6,
"layerName": "postgis:begroeidterreindeel",
"title": "begroeidterreindeel",
"serviceId": 6,
"visible": true,
"minScale": null,
"maxScale": null,
"legendImageUrl": null,
"hiDpiMode": null,
"hiDpiSubstituteLayer": null,
"hasAttributes": true
},
```
eg. when you call https://snapshot.tailormap.nl/api/app/1/map
resolves HTM-543

[HTM-453] send min/max scale as part of the appLayer

---

.gitignore
src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
src/main/resources/application.properties
src/main/resources/tailormap-api.yaml
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
src/test/resources/application-postgresql.properties
src/test/resources/application.properties

see ECQL documentation at https://docs.geotools.org/latest/userguide/library/cql/ecql.html and https://github.com/geotools/geotools/blob/main/modules/library/cql/ECQL.md
Please check the attached integration test for filter examples.
This PR also adds a property to attempt to provide exact feature counts for all (WFS) requests (as some WFS counts will return `-1` this may result in double query execution, once for counting and once for the actual data, default is `false`.
https://github.com/B3Partners/tailormap-api/blob/611d7457cde00c173de3ad1bfd54773b0353ac66/src/main/resources/application.properties#L9-L11
resolves HTM-455

[HTM-455] Implement ECQL filtering for the features endpoint

---

pom.xml
src/main/java/nl/b3p/tailormap/api/controller/UniqueValuesController.java
src/main/resources/application.properties
src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
src/test/resources/application-postgresql.properties
src/test/resources/application.properties

This adds a configuration property `tailormap-api.data.useGeotoolsUniqueFunction` to switch from using SQL "distinct" queries -default/true- to get unique values over to getting all values and process those in memory. The latter may be beneficial for some WFS scenarios.
resolves:
- HTM-457
- HTM-458
- HTM-459
- HTM-473

[HTM-457, HTM-458, HTM-459, HTM-473] Implement unique attributes endpoint for Postgis, Oracle, SQL Server and (Geoserver) WFS

---

pom.xml
src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
src/main/java/nl/b3p/tailormap/api/controller/UniqueValuesController.java
src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java
src/main/resources/application.properties
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessorTest.java
src/test/resources/application-postgresql.properties
src/test/resources/application.properties

Solve the user/admin error of configuring a geometry attribute for display.
- define a configuration property to skip geometry output with features (default `true`)
- output geometry as geojson using GeoTools serializer (JTS was unusable due to conflicting, ancient json dependency)
- also refactored config properties to follow endpoint names
resolves HTM-430

[HTM-430] serialise geometries when configured but skip that by default

---

Dockerfile
build/qa/owasp-suppression.xml

see https://github.com/B3Partners/tailormap-api/security/code-scanning/64

Upgrade the expat library to 2.4.9-r0 to resolve CVE-2022-40674

---

pom.xml
src/main/resources/application.properties
src/main/resources/spy.properties

Uses the standard Sentry environment variables, `SENTRY_DSN` and `SENTRY_TRACES_SAMPLE_RATE`. No other integration other than the default, for now.
The release ID used to link versions to Sentry is the git commit hash. If `SENTRY_DSN` is not set, no Sentry logging will happen.

[HTM-466] enable Sentry

---

Dockerfile
README.md
pom.xml

for now stick to `linux/amd64` and `linux/arm64` (`linux/arm64/v8`)
resolves HTM-527

[HTM-527] set-up multi-arch builds

---

Dockerfile

resolves curl vulnerabilities CVE-2022-32221, CVE-2022-42915 and CVE-2022-42916

Update ubuntu packages before upgrade

---

pom.xml
src/main/java/nl/b3p/tailormap/api/controller/GeoServiceProxyController.java
src/main/java/nl/b3p/tailormap/api/controller/MapController.java
src/main/resources/tailormap-api.yaml
src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerPostgresIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerTest.java
src/test/java/nl/b3p/tailormap/api/controller/MapControllerPostgresIntegrationTest.java

OGC WMS/WMTS proxy

---

src/main/java/nl/b3p/tailormap/api/controller/MapController.java
src/main/resources/model.yaml

(Do we want "opacity" to be sent as 0-100 instead of e.g. 0-1? The viewer uses 0-100, and persistence stores the transparency as 0-100; so it's probably fine.)

HTM-625: Send starting opacity in API

---

pom.xml

Reverts B3Partners/tailormap-api#304
see also https://github.com/B3Partners/tailormap-api/pull/307#issuecomment-1396633892

Revert "Bump dependency-check-maven from 7.4.4 to 8.0.0"

---

src/main/java/nl/b3p/tailormap/api/configuration/TailormapDatabaseInitialization.java
src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestDatabase.java
src/main/java/nl/b3p/tailormap/api/persistence/Catalog.java
src/main/java/nl/b3p/tailormap/api/persistence/GeoServiceCatalog.java
src/main/java/nl/b3p/tailormap/api/repository/CatalogRepository.java
src/main/java/nl/b3p/tailormap/api/repository/GeoServiceCatalogRepository.java
src/main/resources/openapi/persistence-schemas.yaml

I think we should also have feature sources in the catalog tree. WFS services can be added to the same node as the service where they were discovered from and you can categorize them as well.
So the schema would be:
```yaml
CatalogNode:
description: Categorization for items in the catalog.
properties:
id:
type: string
title:
type: string
root:
type: boolean
children:
type: array
items:
type: string
items:
type: array
items:
title: TailormapObjectRef
type: object
properties:
kind:
type: string
enum: ['geo-service', 'feature-source']
id:
type: string
```
Maybe we can also integrate an ArcGIS REST service tree in the future.

Add model for geo service catalog

---

pom.xml

Bumps ojdbc11 from 21.8.0.0 to 21.9.0.0.

Bump oracle-database.version from 21.8.0.0 to 21.9.0.0

---

pom.xml

[HHH-15618](https://hibernate.atlassian.net/browse/HHH-15618) Procedure should accept TypedParameterValue as parameter
[HHH-15665](https://hibernate.atlassian.net/browse/HHH-15665) Mariadb is missing identifier quote on SEQUENCE QUERY
[HHH-16049](https://hibernate.atlassian.net/browse/HHH-16049) Setting a property to its current value with bytecode enhancement enabled results in unnecessary SQL Update in some \(many\) cases
[HHH-15792](https://hibernate.atlassian.net/browse/HHH-15792) Explicitly add JavaDoc to make @deprecated hint for createSQLQuery visible in Eclipse
[HHH-15685](https://hibernate.atlassian.net/browse/HHH-15685) Improve efficiency of Dialect lookup in Loader and HqlSqlWalker
[HHH-15690](https://hibernate.atlassian.net/browse/HHH-15690) HQLQueryPlan to have a direct …

Bump Hibernate from 5.6.14.Final to 5.6.15.Final

---

pom.xml

- Bump `micrometer.version` 1.10.3 ⇨ 1.10.4
- Bump `spring-security.version` 5.8.0 ⇨ 5.8.1
- Bump `postgresql.version` 42.5.3 ⇨ 42.5.4
- Bump `spring-hateoas.version` 1.5.2 ⇨ 1.5.3

♻️ Various dependency updates

---

pom.xml

there doesn't seem to be anything scary with this major version bump: https://flywaydb.org/documentation/learnmore/releaseNotes#9.0.1

Bump flyway.version: 8.5.13 ⇨ 9.15.1

---

pom.xml

see: 
- https://github.com/geotools/geotools/releases/tag/29-RC1

Bump GeoTools from 28.2 to 29-RC1

---

pom.xml
src/main/java/nl/b3p/tailormap/api/security/ActuatorSecurityConfiguration.java

Maven plugins are build-time dependencies, not [compile scope dependencies](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope), they should not end up in the final artifact (runnable jar) of our product

Remove `hibernate-enhance-maven-plugin` from dependencies

---

src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java

The original code tried WMS 1.0.0 first but not much servers support it anymore.
WMS 1.3.0 (the first version GeoTools tries by default) is ok, even if capabilities don't report supporting DescribeLayer, because we `SimpleWFSHelper.describeWMSLayers()` doesn't rely on the capabilities before doing that request (it's currently not automatic anyway, only `PopulateTestData` does it).
Also the noted MapServer WMS which didn't correctly work with WMS 1.1.1 works with WMS 1.3.0.

[HTM-748] Do not override GeoTools WMS version negotiation

---

src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java

disable authenticated tests and add TODO's
some work is left behind to be done after authorisations start to work 
resolves:
- HTM-753
- HTM-754

[HTM-753][HTM-754] cleanup/fixup AppControllerIntegrationTest and LayerDescriptionControllerPostgresIntegrationTest

---

src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
src/main/resources/application-dev.properties
src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerReConfiguredPostgresIntegrationTest.java
src/test/resources/application.properties

[HTM-492] Getting unique values for a timestamp on oracle database gives a 500 error

---

src/main/resources/db/migration/V1__schema.sql
src/main/resources/import.sql

No users should be assigned to these groups and no Spring Security rules should be made on them (only used in `AuthorizationService` to check against authorization rules), remove these groups from the database so they don't show up in the admin.

Remove groups only used for authorization rules

---

pom.xml

resolves dependency check warning for CVE-2022-41853

GeoTools up to 29.1 uses hsqldb 2.5.2, which has CVE-2022-41853, 29.2 will provide 2.7.2

---

pom.xml
src/main/java/nl/b3p/tailormap/api/configuration/TailormapConfig.java
src/main/java/nl/b3p/tailormap/api/controller/admin/ServerSentEventsAdminController.java
src/main/java/nl/b3p/tailormap/api/persistence/Application.java
src/main/java/nl/b3p/tailormap/api/persistence/Catalog.java
src/main/java/nl/b3p/tailormap/api/persistence/Configuration.java
src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java
src/main/java/nl/b3p/tailormap/api/persistence/Group.java
src/main/java/nl/b3p/tailormap/api/persistence/TMFeatureSource.java
src/main/java/nl/b3p/tailormap/api/persistence/TMFeatureType.java
src/main/java/nl/b3p/tailormap/api/persistence/User.java
src/main/java/nl/b3p/tailormap/api/persistence/listener/EntityEventPublisher.java
src/main/resources/application.properties
src/main/resources/openapi/admin-schemas.yaml

Sends events for all entities except `TMFeatureType` (these are included in `TMFeatureSource` events).
Frontend usage:
```
const clientId = Math.floor(Math.random() * 100)); // Or some other method like uuid
const eventSource = new EventSource("/api/admin/events/" + clientId);
eventSource.onmessage = (e) => { 
console.log('event', JSON.parse(e.data));
};
```
Currently this should show all updates except group membership of `User`s. When you delete a group with a lot of members, you do get "updated" events for all users that were a member of that group before the "group deleted" event.
The user admin page does load the user (with groups) when clicking on the user. So this limitation may not be a problem for now.
In the JSON event the id of the entity is included next to the `entityName` …

[HTM-808] Send SSE for entity updates

---

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
src/main/java/nl/b3p/tailormap/api/geotools/TransformationUtil.java
src/main/resources/openapi/viewer-api.yaml
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerReConfiguredIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerIntegrationTest.java

the `crs` parameter is actually useless since #358 and the behaviour is inconsistent with the `edit/feature` endpoint that is agnostic to application crs.
Also cleanup unused code and rename PostgresIntegrationTest to IntegrationTest as all integration tests use PostgreSQL...
resolves HTM-874

[HTM-874] factor out the superfluous `crs` parameter from the `/features` endpoint

---

src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java

[HTM-895] only set writable-true on JDBC-protocol featuretypes

---

pom.xml

Reverts B3Partners/tailormap-api#546
because of https://github.com/fabric8io/docker-maven-plugin/issues/1698

Revert "Bump io.fabric8:docker-maven-plugin from 0.43.0 to 0.43.2"

---

src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
src/main/java/nl/b3p/tailormap/api/controller/LayerExportController.java

`FeaturesController` sorts by first attribute if no primary key, but using unsorted attribute names made this unpredicate and sometimes cause the `FeaturesControllerIntegrationTest.should_return_non_empty_featurecollections_for_valid_page_from_wfs()` test fail because one time the first attribute would be `naam` but sometimes it would be `code`.

Use ordered (configured or original order) where appropriate

---

src/main/java/nl/b3p/tailormap/api/security/AdminAccountCreator.java
src/main/resources/application.properties

This variable was already available in the `populate-testdata` Spring profile but is useful in general too.

Add environment variable for hashed admin password

---

.github/workflows/owasp-dependency-check.yml
.github/workflows/ubuntu-maven.yml
pom.xml

When doing `mvn release:perform`, NVD download is very slow with 8s between downloads instead of 2s without an API key, but running `mvn -DnvdApiKey=... release:perform` does not seem to provide the API key. Setting it in the environment before running `mvn release:perform` with this config should work.

Use NVD API key from environment

---

pom.xml

Logback resolved CVE-2023-6378 and CVE-2023-6481

Bump logback.version override from 1.2.12 to 1.2.13

---

src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java
src/test/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminControllerIntegrationTest.java
src/test/resources/wms/test_capabilities_updated.xml

This should fix slow performance with the default GeoServer settings with all CRSes enabled with quite a few layers considerably. Loading/refreshing the service and proxied requests were very slow because very large JSON needed to be loaded every time with all supported CRSes repeated for every layer.
In this change only new CRSes for child layers are added to the `crs` array. We were not using this `crs` array for anything yet, so new code should take into account that all `crs` values from parent layers are inherited.

HTM-974: Only list additional crses in child layers to save space

---

.github/workflows/macos-maven.yml
.github/workflows/ubuntu-maven.yml
.github/workflows/windows-maven.yml
pom.xml

- Bump jackson-bom.version from 2.16.0 to 2.16.1
- Bump mssql-jdbc.version from 12.4.1.jre11 to 12.4.2.jre11
- Bump micrometer.version from 1.12.0 to 1.12.2
- Bump spring-security.version from 5.8.8 to 5.8.9
- Add json-path.version override to resolve CVE-2023-51074 
- Bump mssql-jdbc.version from 12.4.2.jre11 to 12.6.0.jre11
- Update codecov/codecov-action from v3 to v4

Dependency updates

---

src/main/java/nl/b3p/tailormap/api/persistence/Application.java
src/main/java/nl/b3p/tailormap/api/repository/validation/ApplicationValidator.java
src/main/java/nl/b3p/tailormap/api/repository/validation/ValidationConfiguration.java
src/main/resources/db/migration/V4__app_name_unique.sql
src/test/java/nl/b3p/tailormap/api/controller/admin/ApplicationAdminControllerIntegrationTest.java

POST http://localhost:4200/api/admin/applications
with body:
```json
{"name":"default","title":"testerdetest","adminComments":"","crs":"EPSG:28992","initialExtent":null,"maxExtent":null,"authorizationRules":[{"groupName":"anonymous","decisions":{"read":"allow"}}],"settings":{"layerSettings":{},"i18nSettings":{"defaultLanguage":null,"hideLanguageSwitcher":false},"uiSettings":{"hideLoginButton":false}}}
```
Response HTTP 409 Conflict:
```json
{
"cause": {
"cause": {
"cause": null,
"message": "ERROR: duplicate key value violates unique constraint \"uk_lspnba25gpku3nx3oecprrx8c\"\n  Detail: Key (name)=(default) already exists."
},
"message": "could not execute statement"
},
"message": "could not execute statement; SQL [n/a]; constraint [uk_lspnba25gpku3nx3oecprrx8c]; nested exception is …
```

HTM-1025: Application name must be unique

---

.github/workflows/ubuntu-maven.yml
.mvn/maven.config
build/ci/docker-compose.yml

So that you can suffice running the shell script to brink up all the databases needed for full CI

[infra] Move postgres service to compose file

---

pom.xml

Version 42.7.2 has a resolution for CVE-2024-1597

Update pgjdbc to 42.7.2 to workaround CVE-2024-1597, also update mssql jdbc driver to latest patch version

---

.github/workflows/macos-maven.yml
.github/workflows/owasp-dependency-check.yml
.github/workflows/qa.yml
.github/workflows/trivy.yml
.github/workflows/ubuntu-maven.yml
.github/workflows/windows-maven.yml
.mvn/jvm.config
Dockerfile
pom.xml

Upgrade to Java 17, this is the first step towards upgrading to Spring Boot 3.x which requires Java 17 as a baseline.
resolves HTM-1036

[HTM-1036] Java 17 compiler and runtime upgrade

---

pom.xml

see https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md#version-9010-2024-03-15

Bump dependency-check-maven.version from 9.0.9 to 9.0.10

---

.github/workflows/codeql-analysis.yml
.github/workflows/ubuntu-maven.yml
.github/workflows/windows-maven.yml

CodeQL Java builds are failing, presumably because of a too low Maven version

[CI] all builds require Maven 3.9.5 or higher

---

pom.xml

Bump GeoTools from 30.2 to 31.0

---

src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java

The FeaturesControler only uses POST for an idempotent request because the filter can possibly be too large for a URL query parameter so with a POST request the filter can be sent in the request body. Disable CSRF protection for this controller so feature info requests etc. can be used when Tailormap is embedded an iframe when the XSRF token can't be read from the 3rd party cookie (even with SameSite=None, with strict browser protection settings this is still blocked by some current browsers which have those by default).

HTM-1032: Disable CSRF filter for FeaturesController 

---

src/main/java/nl/b3p/tailormap/api/persistence/Group.java
src/main/resources/db/migration/V6__group_additional_properties.sql

For https://github.com/B3Partners/tailormap-viewer/pull/610
User already has `additionalProperties` (currently not used for anything I think)

Add additional properties to Group

---

build/ci/docker-compose.yml
pom.xml
src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/nl/b3p/tailormap/api/controller/SearchController.java
src/main/java/nl/b3p/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java
src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java
src/main/java/nl/b3p/tailormap/api/persistence/SearchIndex.java
src/main/java/nl/b3p/tailormap/api/repository/SearchIndexRepository.java
src/main/java/nl/b3p/tailormap/api/solr/FeatureDocument.java
src/main/java/nl/b3p/tailormap/api/solr/FeatureIndexingDocument.java
src/main/java/nl/b3p/tailormap/api/solr/SolrHelper.java
src/main/java/nl/b3p/tailormap/api/solr/SolrUtil.java
src/main/java/nl/b3p/tailormap/api/util/Constants.java
src/main/resources/application.properties
src/main/resources/db/migration/V7__indexing_metadata_entity.sql
src/main/resources/openapi/persistence-schemas.yaml
src/main/resources/openapi/viewer-api.yaml
src/test/java/nl/b3p/tailormap/api/controller/SearchControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerIntegrationTest.java
src/test/java/nl/b3p/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java
src/test/resources/application-postgresql.properties

related: https://github.com/B3Partners/tailormap-viewer/pull/571
All Solr logic is implemented in the `solr` package. There are two main classes in the package: `SolrHelper` and `FeatureIndexingDocument`.
The `SolrHelper` class is responsible for interacting with the Solr service, the `FeatureIndexingDocument` class is a POJO that models the mapping from a Feature to a Solr document.
The `admin/index` (GET) method of the `SolrAdminController` class is used to check if the Solr service is up and running using a ping.
The `admin/index` (PUT) method of the `SolrAdminController` class is used to index the feature type associated with a layer in the catalog.
The `admin/index` (DELETE) method of the `SolrAdminController` class is used to delete the index of the feature type associated with a …

[HTM-1058] Solr indexing and API

---

build/ci/docker-compose.yml
src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java

Note that the existing Oracle container + volume must be dropped/recreated and GeoServer will need an updated database connection, see https://github.com/B3Partners/containers/pull/556
resolves HTM-1127

[HTM-1127] Change XEPDB1 to FREEPDB1 so we can benefit from the Oracle upgrade to 23.4

---

pom.xml

- Bump dependency-check-maven.version from 9.2.0 to 10.0.1
- ~~Bump openapi-generator-maven-plugin from 7.6.0 to 7.7.0~~ reverted
- Bump flyway.version from 10.15.0 to 10.15.2
- Bump mssql-jdbc.version from 12.6.2.jre11 to 12.6.3.jre11

Maven and dependency updates

---

pom.xml

[![HTM-1196](https://badgen.net/badge/JIRA/HTM-1196/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1196) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
resolves [HTM-1196]
this should fix:
- https://github.com/Tailormap/tailormap-api/security/dependabot/4
- https://github.com/Tailormap/tailormap-api/security/dependabot/3
- https://github.com/Tailormap/tailormap-api/security/code-scanning/349
[HTM-1196]: https://b3partners.atlassian.net/browse/HTM-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1196: Spring Boot 3.3.3 and other dependency updates

---

pom.xml

Bumps org.apache.commons:commons-lang3 from 3.16.0 to 3.17.0.

Bump org.apache.commons:commons-lang3 from 3.16.0 to 3.17.0

---

src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java

as tracked in https://b3partners.atlassian.net/browse/HTM-1198 this may be caused by a behavioural change in GeoServer

Disable LayerExportControllerIntegrationTest#shouldNotExportHiddenAttributesInGeoJSON

---

.github/workflows/codeql.yml

The tool complains about 'Low Java analysis quality' after https://github.com/Tailormap/tailormap-api/pull/929
> Scanning Java code completed successfully, but the scan encountered issues. This may be caused by problems identifying dependencies or use of generated source code, among other reasons -- see other CodeQL diagnostics reported on the CodeQL status page for more details of possible causes. Addressing these warnings is advisable to avoid false-positive or missing results. If they cannot be addressed, consider scanning Java using either the autobuild or manual [build modes](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#comparison-of-the-build-modes).

Generate sources before running CodeQL

---

src/main/resources/application-dev.properties
src/main/resources/application.properties

[![HTM-1162](https://badgen.net/badge/JIRA/HTM-1162/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1162) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Also make the logging config for the default profile more appropriate for production use.
The default log rotation settings are used:
https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.file-rotation
[HTM-1162]: https://b3partners.atlassian.net/browse/HTM-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1162: Configure logfile so it can be retrieved using actuator

---

pom.xml

Reverts Tailormap/tailormap-api#857
see https://github.com/B3Partners/jdbc-util/pull/630

Revert "Bump org.apache.maven.plugins:maven-scm-publish-plugin from 3.2.1 to 3.3.0"

---

src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/org/tailormap/api/repository/validation/SearchIndexValidator.java
src/main/java/org/tailormap/api/repository/validation/ValidationConfiguration.java
src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java

[![HTM-1206](https://badgen.net/badge/JIRA/HTM-1206/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1206) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Throw an error when a request to index a WFS feature type is received in the indexing controller, this should never happen because it should not be possible to create an index in a wfs feature type.
When you try to create a search index on a wfs:
```javascript
fetch("http://localhost:8080/api/admin/search-indexes", {
"headers": {
"accept": "application/json, text/plain, */*",
"accept-language": …
```

HTM-1206: disable Solr indexing for WFS feature types

---

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/controller/SearchController.java
src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/org/tailormap/api/repository/FeatureSourceRepository.java
src/main/java/org/tailormap/api/repository/FeatureTypeRepository.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/main/java/org/tailormap/api/solr/SolrService.java
src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java

- Introduce the SolrService from PR #844
- make the SearchIndexValidatorIntegrationTest more robust to changes and differences in the persisted test data 
- resolve GeoTools logging the message "There's code using JDBC based datastore and not disposing them. This may lead to temporary loss of database connections. Please make sure all data access code calls DataStore.dispose() before freeing all references to it" by explicitly calling `dispose()`.

HTM-1211: Some code improvements for Solr functionality

---

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/controller/FeaturesController.java
src/main/resources/openapi/persistence-schemas.yaml
src/main/resources/openapi/viewer-api.yaml
src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java

[![HTM-1160](https://badgen.net/badge/JIRA/HTM-1160/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1160) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1160]: https://b3partners.atlassian.net/browse/HTM-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1160: Allow configuration of template for feature type

---

pom.xml

[![HTM-1039](https://badgen.net/badge/JIRA/HTM-1039/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1039) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Releases are expected first half of September, see [GeoServer Release Schedule](https://github.com/geoserver/geoserver/wiki/Release-Schedule) and [JTS release plan](https://projects.eclipse.org/projects/locationtech.jts/releases/1.20.0/plan)
see also: https://github.com/geoserver/geoserver/wiki/Release-Schedule#volunteer-coordination
[HTM-1039]: https://b3partners.atlassian.net/browse/HTM-1039?atlOrigin=eyJpIjoiNWRkNTljNz …

HTM-1039: Upgrade to GeoTools 32.0 / JTS 1.20.0

---

build/qa/owasp-suppression.xml

[![HTM-1243](https://badgen.net/badge/JIRA/HTM-1243/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1243) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1243: Suppress some irrelevant CVEs in OWASP scanner

---

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
src/main/java/org/tailormap/api/scheduling/TaskCreator.java
src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java

[![HTM-1225](https://badgen.net/badge/JIRA/HTM-1225/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1225) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Quartz default value is 5, we should stick with positive values
[HTM-1225]: https://b3partners.atlassian.net/browse/HTM-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1225: implement prioritising job triggers

---

pom.xml
src/main/java/org/tailormap/api/configuration/SchedulerConfiguration.java
src/main/java/org/tailormap/api/scheduling/TaskCreator.java

[![HTM-1227](https://badgen.net/badge/JIRA/HTM-1227/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1227) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1227: allow monitoring of triggered jobs through Sentry

---

pom.xml

[![HTM-1259](https://badgen.net/badge/JIRA/HTM-1259/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1259) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
- Bump flyway.version from 10.18.2 to 10.19.0
- Bump micrometer.version from 1.13.4 to 1.13.6
- ~Bump jackson-bom.version from 2.17.2 to 2.18.0~
[HTM-1259]: https://b3partners.atlassian.net/browse/HTM-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1259: Dependency updates: flyway, micrometer

---

src/main/java/org/tailormap/api/configuration/base/WebMvcConfig.java
src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
src/main/java/org/tailormap/api/persistence/SearchIndex.java
src/main/java/org/tailormap/api/repository/SearchIndexRepository.java
src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
src/main/java/org/tailormap/api/scheduling/FailingPocTask.java
src/main/java/org/tailormap/api/scheduling/IndexTask.java
src/main/java/org/tailormap/api/scheduling/PocTask.java
src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
src/main/java/org/tailormap/api/scheduling/Task.java
src/main/java/org/tailormap/api/scheduling/TaskCreator.java
src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
src/main/java/org/tailormap/api/scheduling/TaskType.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/main/resources/db/migration/V11__add_solr_index_schedule_column.sql
src/main/resources/openapi/admin-schemas.yaml
src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java

[![HTM-1254](https://badgen.net/badge/JIRA/HTM-1254/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1254) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
- scheduled 1 indexing task
[HTM-1254]: https://b3partners.atlassian.net/browse/HTM-1254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1255]: https://b3partners.atlassian.net/browse/HTM-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1256]: https://b3partners.atlassian.net/browse/HTM-1256?atlOrigin=eyJpIjoiNWRkNTljNz …

HTM-1254|HTM-1255|HTM-1256|HTM-1257: Make creating full-text indexes on schedule as part of task framework possible

---

src/main/resources/application.properties

[![HTM-1253](https://badgen.net/badge/JIRA/HTM-1253/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1253) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
this may or may not help, see eg. https://stackoverflow.com/questions/22754318/quartz-job-retrigerring-after-server-shutdown 
[HTM-1253]: https://b3partners.atlassian.net/browse/HTM-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1253: fix java.lang.IllegalStateException: JobStore is shutdown - aborting retry

---

src/main/java/org/tailormap/api/solr/SolrHelper.java

[![HTM-1266](https://badgen.net/badge/JIRA/HTM-1266/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
**⛓️‍💥 Note: when upgrading you may need to drop the Solr core or at least the schema so full-text indexes can be recreated with the correct type** 
It is not sufficient to delete the indexes, because that will not create a new schema in the `tailormap` Solr core.
[HTM-1266]: https://b3partners.atlassian.net/browse/HTM-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

⛓️‍💥 HTM-1266: explicitly create the INDEX_DISPLAY_FIELD and INDEX_SEARCH_FIELD to make sure these are of the required type ⛓️‍💥

---

pom.xml

- [HTM-1251](https://b3partners.atlassian.net/browse/HTM-1251): Upgrade Spring Boot from 3.3.4 to 3.3.5
- Rely on the `spring-security.version` provided by Spring Boot
- Rely on Spring Boot provided versions of `spring-data-bom` and `spring-hateoas`
- [HTM-1289](https://b3partners.atlassian.net/browse/HTM-1289): Bump flyway.version from 10.19.0 to 10.20.1
this should resolve:
- https://github.com/Tailormap/tailormap-api/security/code-scanning/364
- https://github.com/Tailormap/tailormap-api/security/dependabot/7
[HTM-1251]: https://b3partners.atlassian.net/browse/HTM-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1289]: https://b3partners.atlassian.net/browse/HTM-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

HTM-1251: Upgrade Spring Boot from 3.3.4 to 3.3.5, rely on the `spring-security.version` provided by Spring Boot

---

build/ci/docker-compose.yml
src/main/java/org/tailormap/api/controller/SearchController.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/main/resources/openapi/viewer-api.yaml
src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java

[![HTM-1091](https://badgen.net/badge/JIRA/HTM-1091/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1091) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
**⛓️‍💥 Note: when upgrading you will need to fully redeploy the Solr service (including dropping any associated volumes) so full-text indexes can be recreated with the correct geometry type** 
Exposes extra search API parameters:`d`, `pt` and `fq`: 
https://github.com/Tailormap/tailormap-api/blob/a3606232367a595164dde95938b7b1092ab7a91e/src/main/resources/openapi/viewer-api.yaml#L1312-L1330
requires …

⛓️‍💥 HTM-1091: Add feature geometry as a strong-type ⛓️‍💥

---

src/main/java/org/tailormap/api/controller/LayerExportController.java
src/main/resources/application.properties
src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
src/test/resources/application.properties

[![HTM-1286](https://badgen.net/badge/JIRA/HTM-1286/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1286) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Fixes [https://github.com/Tailormap/tailormap-api/security/code-scanning/352](https://github.com/Tailormap/tailormap-api/security/code-scanning/352)
To fix the SSRF vulnerability, we need to validate the user-provided input (`outputFormat`) against a list of allowed values. This ensures that only legitimate and expected values are used to construct the WFS request URI.
1. Define a list of allowed `outputFormat` values. …

HTM-1286: Fix code scanning alert no. 352: Server-side request forgery

---

pom.xml

this uses the Jakarta namespace, which is the most notable change compared to 2.4.0 (see https://github.com/Tailormap/tailormap-api/pull/1034)
see: https://github.com/quartz-scheduler/quartz/releases/tag/v2.5.0

Bump quartz.version from 2.4.0 to 2.5.0

---

src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
src/main/java/org/tailormap/api/scheduling/TaskManagerService.java

* When a search index is updated the schedule.priority attribute can be null. This is now checked, and if the value is null, the default value is used.
* The type attribute of a task is converted to a string when updating a task in the TaskManagerService.

Allow schedule to have `null` priority when updating a search index

---

build/ci/docker-compose.yml
pom.xml
src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/controller/SearchController.java
src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/org/tailormap/api/scheduling/IndexTask.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/main/java/org/tailormap/api/solr/SolrService.java
src/main/resources/application.properties

[![HTM-1332](https://badgen.net/badge/JIRA/HTM-1332/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Use a Http2SolrClient (the async, non-blocking and general-purpose client that leverage HTTP/2 using the Jetty Http library) instead of a `ConcurrentUpdateHttp2SolrClient` (geared towards indexing-centric workloads. Buffers documents internally before sending larger batches to Solr) to prevent timeouts when submitting large sets of documents. This trades stability over performance; however many connection and indexing …

⛓️‍💥 HTM-1332: fix Solr indexing timeouts ⛓️‍💥

---

src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java

This was previously added for updating an existing task, but not yet for a new task.

Allow priority to be null when creating a new task

---

build/ci/docker-compose.yml

this may still need some work, but will/should enable e.g. IntelliJ to connect to a remote instance which could be equipped with more resources, eg from home to a server or office desktop

Add a devcontainer config

---

src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
src/main/java/org/tailormap/api/persistence/SearchIndex.java
src/main/java/org/tailormap/api/scheduling/IndexTask.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/main/resources/db/migration/V13__add_solr_index_summary_delete_comment_columns.sql
src/main/resources/openapi/admin-schemas.yaml

[![HTM-1366](https://badgen.net/badge/JIRA/HTM-1366/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1366) [![HTM-1367](https://badgen.net/badge/JIRA/HTM-1367/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1367) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
_**Note** that this requires changes in the viewer_:https://github.com/Tailormap/tailormap-viewer/pull/783
[HTM-1366]: https://b3partners.atlassian.net/browse/HTM-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1367]: …

HTM-1366 | HTM-1367: Indexing process summary information should be stored as a json blob

---

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java
src/test/java/org/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
src/test/java/org/tailormap/api/controller/PageControllerIntegrationTest.java
src/test/java/org/tailormap/api/controller/TestUrls.java
src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java

…at all (not even will a null value), instead of doesNotExist() which passes for null values
Should work when a GeoServer with fix for GEOT-7673 is released.

Fix: use doesNotHaveJsonPath() when expecting that a path should not exist

---

pom.xml

resolve 
- HTM-1393 / https://github.com/Tailormap/tailormap-api/security/dependabot/8
- HTM-1394 / https://github.com/Tailormap/tailormap-api/security/dependabot/9

HTM-1393 | HTM-1394: Override logback version provided by Spring Boot bom from 1.5.12 to 1.5.14

---

src/main/java/org/tailormap/api/configuration/base/FrontControllerResolver.java
src/main/java/org/tailormap/api/configuration/base/IndexHtmlTransformer.java
src/main/java/org/tailormap/api/configuration/base/WebMvcConfig.java
src/main/resources/application.properties

Front controller fixes

---

pom.xml

- HTM-1399: Bump `sentry.version`: 7.19.1 to 7.20.0
- HTM-1400: Bump `micrometer.version` 1.13.6 -> 1.14.2

HTM-1399|HTM-1400: Dependency updates

---

src/main/java/org/tailormap/api/solr/SolrHelper.java

[![HTM-1413](https://badgen.net/badge/JIRA/HTM-1413/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1413) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
because there are no fields to copy, where a NonNull is required
[HTM-1413]: https://b3partners.atlassian.net/browse/HTM-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1413: when there are no attributes left indexing could crash

---

src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java

[![SUPPORT-14840](https://badgen.net/badge/JIRA/SUPPORT-14840/pink?icon=jira)](https://b3partners.atlassian.net/browse/SUPPORT-14840) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
GeoServer was updated to 2.26.2 which should have this fixed
[SUPPORT-14840]: https://b3partners.atlassian.net/browse/SUPPORT-14840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SUPPORT-14840: re-enable and fix the `shouldNotExportHiddenAttributesInGeoJSON` testcase

---

src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
src/main/java/org/tailormap/api/solr/SolrHelper.java
src/test/java/org/tailormap/api/solr/SolrHelperIntegrationTest.java

[![HTM-1428](https://badgen.net/badge/JIRA/HTM-1428/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Creating indexes from feature types that have no primary keys or (default) geometry is not supported (it would prevent linking back to the original feature as well as spatial filtering)
[HTM-1428]: https://b3partners.atlassian.net/browse/HTM-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1428: prevent NPE when a feature type has no primary key or geometry and admin erroneously wants to create a Solr index from it

---

pom.xml

[![CVE-2024](https://badgen.net/badge/JIRA/CVE-2024/pink?icon=jira)](https://b3partners.atlassian.net/browse/CVE-2024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[![HTM-1436](https://badgen.net/badge/JIRA/HTM-1436/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1436)
Netplex Json-smart has resolved, see: https://github.com/Tailormap/tailormap-api/security/dependabot/11 and https://github.com/Tailormap/tailormap-viewer/security/code-scanning/325
[HTM-1436]: https://b3partners.atlassian.net/browse/HTM-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

[HTM-1436] Override json-smart.version to obtain a version that has fixed CVE-2024-57699

---

build/ci/testdata-setup.sh
src/main/java/org/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
src/test/java/org/tailormap/api/controller/EditFeatureControllerIntegrationTest.java

[![HTM-1441](https://badgen.net/badge/JIRA/HTM-1441/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Previously a feature type was set as writeable when the feature source was JDBC, but the GeoTools JDBC data store also sets a user data read only property that more accurately reflects whether the feature type is writeable.
[HTM-1441]: https://b3partners.atlassian.net/browse/HTM-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1441: set writeable property when JDBC feature type is not read only and no composite keys are found

---

src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java

[![HTM-1451](https://badgen.net/badge/JIRA/HTM-1451/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
disabled until 2025-04-03, the capabilities document specifies a legend image that does not exist
[HTM-1451]: https://b3partners.atlassian.net/browse/HTM-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1451: temporarily disable failing PDOK service legend test

---

pom.xml

[![HTM-1477](https://badgen.net/badge/JIRA/HTM-1477/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1477) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
fixes:
- https://github.com/Tailormap/tailormap-api/security/dependabot/12
- https://github.com/Tailormap/tailormap-api/security/code-scanning/383
- https://github.com/Tailormap/tailormap-api/security/code-scanning/382
- https://github.com/Tailormap/tailormap-api/security/code-scanning/381
[HTM-1477]: https://b3partners.atlassian.net/browse/HTM-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

HTM-1477: update Spring Boot parent (includes Spring Security) to resolve CVE-2025-22228

---

pom.xml

see https://github.com/fabric8io/docker-maven-plugin/releases/tag/v0.46.0
Also bump our project version to [12.0.0-SNAPSHOT](https://b3partners.atlassian.net/projects/HTM/versions/10468/tab/release-report-all-issues) as that is what we're working on

Bump io.fabric8:docker-maven-plugin from 0.45.1 to 0.46.0

---

.github/workflows/macos-maven.yml
.github/workflows/reuse.yml
.github/workflows/ubuntu-maven.yml

Potential fix for [https://github.com/Tailormap/tailormap-api/security/code-scanning/394](https://github.com/Tailormap/tailormap-api/security/code-scanning/394)
To fix the issue, we will add a `permissions` block to the `cleanup` job in the workflow file. Since the `cleanup` job only performs Maven cache cleanup and does not interact with the repository or other GitHub resources, we can set the permissions to `contents: read` as a minimal starting point. This ensures that the job has the least privileges required to execute.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

some fixes for "Workflow does not contain permissions"

---

pom.xml

<details>
<summary>geotools/geotools</summary>
[Compare Source](https://redirect.github.com/geotools/geotools/compare/33.0...33.1)
</details>

Update geotools.version to v33.1

---

build/qa/owasp-suppression.xml
pom.xml

[![HTM-1542](https://badgen.net/badge/JIRA/HTM-1542/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1542) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
- Jackson 2.18.4
- Spring Security 6.4.6
- Spring Framework 6.2.7
- ... etc
Fixes https://github.com/Tailormap/tailormap-api/security/code-scanning/395 and https://github.com/Tailormap/tailormap-api/security/code-scanning/387
[HTM-1542]: https://b3partners.atlassian.net/browse/HTM-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1542: Update Spring Boot and other dependencies

---

pom.xml

[![HTM-1569](https://badgen.net/badge/JIRA/HTM-1569/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1569) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
resolves https://github.com/Tailormap/tailormap-api/security/dependabot/14 / CVE-2025-49146
[HTM-1569]: https://b3partners.atlassian.net/browse/HTM-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1569: Bump postgresql.version from 42.7.6 to 42.7.7

---

pom.xml

- Override com.nimbusds:nimbus-jose-jwt to 9.37.4 for CVE-2025-53864 (https://github.com/Tailormap/tailormap-api/security/dependabot/20) / https://github.com/Tailormap/tailormap-api/security/code-scanning/407)
- Bump hibernate.version from 6.6.24.Final to 6.6.25.Final
- Bump mssql-jdbc.version from 12.10.1.jre11 to 13.2.0.jre11
- Bump micrometer.version from 1.15.2 to 1.15.3

Assorted dependency updates

---

pom.xml

resolves https://github.com/Tailormap/tailormap-api/security/dependabot/22

Bump Solr jetty.version override from 10.0.24 to 10.0.26

---

build/ci/compose-config-files/prometheus.yaml
src/main/java/org/tailormap/api/security/ActuatorSecurityConfiguration.java
src/test/java/org/tailormap/api/security/ActuatorSecurityConfigurationIntegrationTest.java

This allows prometheus to scrape without a password.

Allow actuator access from internal networks and localhost

---

src/main/java/org/tailormap/api/prometheus/PrometheusService.java
src/main/java/org/tailormap/api/repository/events/ApplicationEventHandler.java
src/test/java/org/tailormap/api/prometheus/PrometheusServiceIntegrationTest.java
src/test/java/org/tailormap/api/repository/events/ApplicationEventHandlerIntegrationTest.java

[![HTM-1600](https://badgen.net/badge/JIRA/HTM-1600/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1600) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Use the `@HandleAfterDelete` repository event to handle cleanup
[HTM-1600]: https://b3partners.atlassian.net/browse/HTM-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1600: Cleanup the application and application layer metrics when an application is deleted

---

src/main/java/org/tailormap/api/controller/admin/PrometheusDataController.java
src/main/java/org/tailormap/api/prometheus/PrometheusService.java

It's a normal use case to deploy without Prometheus so no warnings or stack traces in that case.

Reduce log output when Prometheus is not available
